---
ospf_configer:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 101
          neighbor:
          - ip: 10.2.0.4
          network:
          - area: 0
            ip: 10.2.0.0
            wildcard: 0.0.0.255
          - area: 2
            ip: 20.20.20.0
            wildcard: 0.0.0.255
          router-id: 2.2.2.2
          passive-interface:
              default: false

loopback:
  Cisco-IOS-XE-native:interface:
    Loopback:
    - ip:
        address:
          primary:
            address: 20.20.20.1
            mask: 255.255.255.0
      name: 0

interface:
  Cisco-IOS-XE-native:GigabitEthernet:
    Cisco-IOS-XE-ethernet:negotiation:
      auto: true
    ip:
      Cisco-IOS-XE-nat:nat:
        outside:
        -
      Cisco-IOS-XE-ospf:router-ospf:
        ospf:
          network:
            non-broadcast:
            -
      address:
        dhcp: {}
    mop:
      enabled: false
      sysid: false
    name: '1'

banner:
  banner: Dit is R2 voor de I-share kennissessie.